spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://${song-db-domain:localhost}:${song-db-port:5434}/song_db
    username: ${song-db-username:postgres}
    password: ${song-db-password:}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081

song:
  allowed-csv-length: 200