spring:
  application:
    name: resource-client
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://${resource-db-domain:localhost}:${resource-db-port:5433}/resource_db
    username: ${resource-db-username:postgres}
    password: ${resource-db-password:}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

resource:
  allowed-csv-length: 200

song:
  api:
    #url: http://${song-domain:localhost}:8081/api/v1
    url: http://${api-gateway-domain:localhost}:8088/api/v1

server:
  port: 8080

eureka.client.serviceUrl.defaultZone: http://${discovery-service-domain:localhost}:8761/eureka
